### ISSUE TITLE
Software defect detected

### ISSUE THREAD

**Issue by mostym** [oudoken/static_cache#5]
When the user is not logged into the site, I get the following: 
```
Software defect detected; ob_*() level 2 at end instead of (1). POPPING EXTRA BUFFERS!
```

**Comment by oudoken** [comment]
Hi mostym,
What version of e107 and php are You using?

**Comment by mostym** [comment]
I'm using the GitHub 2.19 version and php 7.2  Thanks!

**Comment by oudoken** [comment]
ok i will check it out

**Comment by mostym** [comment]
I see the following in my nginx error log

```
2019/01/30 15:47:42 [error] 23491#23491: *7484431 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /var/www/mydomain.com/e107_plugins/static_cache/e_output.php:20
Stack trace:
#0 /var/www/mydomain.com/e107_core/templates/footer_default.php(388): include_once()
#1 /var/www/mydomain.com/login.php(122): require_once('/var/www/mydoma...')
#2 {main}
  thrown in /var/www/mydomain.com/e107_plugins/static_cache/e_output.php on line 20" while reading response header from upstream, client: 78.195.25.65, server: www.mydomain.com, request: "POST /login.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.mydomain.com", referrer: "https://www.mydomain.com/login.php"
2019/01/30 15:48:44 [error] 23491#23491: *7485769 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /var/www/mydomain.com/e107_plugins/static_cache/e_output.php:20
Stack trace:
#0 /var/www/mydomain.com/e107_core/templates/footer_default.php(388): include_once()
#1 /var/www/mydomain.com/signup.php(1078): require_once('/var/www/mydoma...')
#2 {main}
  thrown in /var/www/mydomain.com/e107_plugins/static_cache/e_output.php on line 20" while reading response header from upstream, client: 71.198.237.112, server: www.mydomain.com, request: "GET /signup.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.mydomain.com", referrer: "https://www.mydomain.com/download/78677/3ds0493-animal-crossing-new-leaf-usa-decrypted"
2019/01/30 15:49:43 [error] 23491#23491: *7460767 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /var/www/mydomain.com/e107_plugins/static_cache/e_output.php:20
Stack trace:
#0 /var/www/mydomain.com/e107_core/templates/footer_default.php(388): include_once()
#1 /var/www/mydomain.com/signup.php(1078): require_once('/var/www/mydoma...')
#2 {main}
  thrown in /var/www/mydomain.com/e107_plugins/static_cache/e_output.php on line 20" while reading response header from upstream, client: 49.146.187.58, server: www.mydomain.com, request: "GET /signup.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.mydomain.com", referrer: "https://www.mydomain.com/download/78899/3ds1751-monster-hunter-stories-usa"
2019/01/30 15:49:57 [error] 23491#23491: *7485769 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /var/www/mydomain.com/e107_plugins/static_cache/e_output.php:20
Stack trace:
#0 /var/www/mydomain.com/e107_core/templates/footer_default.php(388): include_once()
#1 /var/www/mydomain.com/signup.php(979): require_once('/var/www/mydoma...')
#2 {main}
  thrown in /var/www/mydomain.com/e107_plugins/static_cache/e_output.php on line 20" while reading response header from upstream, client: 71.198.237.112, server: www.mydomain.com, request: "POST /signup.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.mydomain.com", referrer: "https://www.mydomain.com/signup.php"
```

**Comment by mostym** [comment]
Also getting this:

```
2019/01/30 15:55:10 [error] 23491#23491: *7502785 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught phpFastCache\Exceptions\phpFastCacheIOException: PLEASE CHMOD /var/www/mydomain.com/e107_web/cache/mydomain.com/Files/20/9d - 511 OR ANY WRITABLE PERMISSION!
Additional information provided by error_get_last():
ob_end_clean(): failed to delete buffer. No buffer to delete in /var/www/mydomain.com/class2.php line 67 in /var/www/mydomain.com/e107_plugins/static_cache/libs/phpfastcache/src/phpFastCache/Core/Pool/IO/IOHelperTrait.php:157
Stack trace:
#0 /var/www/mydomain.com/e107_plugins/static_cache/libs/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(72): phpFastCache\Drivers\Files\Driver->getFilePath('1b98d966e6c8652...')
#1 /var/www/mydomain.com/e107_plugins/static_cache/libs/phpfastcache/src/phpFastCache/Core/Pool/CacheItemPoolTrait.php(358): phpFastCache\Drivers\Files\Driver->driverWrite(Object(phpFastCache\Drivers\Files\Item))
#2 /var/www/mydomain.com/e107_plugins/static_cache/e_output.php(22): phpFastCache\Drivers\Files\Driver->save(Ob" while reading response header from upstream, client: 109.95.126.231, server: www.mydomain.com, request: "GET /download/31176/bk-7473-linda-howard-game-of-chance-after-the-night-almost-forever-burn-come-lie-with-me-cry-no-more HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www.mydomain.com"
```

**Comment by oudoken** [comment]
Hi i've installed the latest GH version of e107 and seems working ok (at least on php 7.1.2).
So i am unable to reproduce the problem.
Maybe try to lower php version and see if helps?

**Comment by mostym** [comment]
I noticed that this error occurs when you have the e107 developer mode enabled.

**Comment by oudoken** [comment]
Ah! ok i will check into this Thanks
